// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cugkaynjnckzxgxgyzva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1Z2theW5qbmNrenhneGd5enZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjAxMTcsImV4cCI6MjA2MjA5NjExN30.-5_MiUvPMlZBcrlWmYPbcJ9Rn1cDaV9g_OO4IOyzNrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);